### ISSUE TITLE
Add max_zoom_level configuration for in-game zoom

### ISSUE THREAD

**Issue by DopiePanda** [selb/YumLife#28]
When zooming out too far the game will sometimes crash. I believe it happens when you zoom out at the same time as loading in a new world chunk.

I believe that if we are able to set a maximum level for zooming out, we can avoid having to think about how to fix the actual issue. <3

**Comment by selb** [comment]
v399d allows limiting zoom in this way. I'm not convinced that will solve the crashes, because I suspect it has something to do with the way certain vanilla UI animations are fiddled with. But try to reduce `zoom_limit` if it still crashes at the default and let me know if there's a value that really stops the crashes, as that might help track down the actual issue.
