### ISSUE TITLE
Accounts Which Aren't in Game

### ISSUE THREAD

**Issue by DougLefelhocz** [selb/YumLife#42]
It used to be that using '.list' only gave accounts of players currently online, in game (or at least so I thought).

However, now it seems that players who aren't online still get registered by '.list'.  I saw on iamdox's stream my PXname, but I wasn't online at the time.  Currently, I also see an "Eve Ginger" as if that person was playing now, even though that person died 2 days ago.

It does seem to remove some people who aren't currently in game, but it doesn't seem consistent.  And I don't understand why anyone who dies in a life should remain in the list until they log in another life.

**Comment by selb** [comment]
YumLife now stays connected to the Phex server between lives, so at least some of these are people leaving the client open after a life. There could also be changes to this behavior in the new Phex server.

I'll change the behavior so that Phex users whose reported lives have ended and who haven't been observed speaking in Phex in a while will be hidden from `.list` output.
