### ISSUE TITLE
Player takes Backpack off sometimes when you press Q

### ISSUE THREAD

**Issue by Stabbn** [selb/YumLife#48]
Backpack comes off sometimes when you press Q to access items in bag.

**Comment by selb** [comment]
Based on initial testing, this is how it happens:

- have item in hand
- drop item
- before server acknowledges you have dropped it, press Q
- Q code thinks you still have an item in hand and sends SELF message, which drops bp when you have nothing in hand to put in bp

Need to track when there is a DROP received by the server but not yet acknowledged in a PU so that the `useBackpack()` SELF/SREMV conditional aligns with the expected future server state at the time of the new message being received.

**Comment by selb** [comment]
oh my goose it works

**Comment by selb** [comment]
fixed in 87258601f543a0658f03bd02a6d15e93be90d486

**Comment by selb** [comment]
There's another case where this happens:
- have item in hand
- combine item onto the current tile (for instance, "dropping" a piece of iron ore onto a stack)
- before server acknowledges, press Q
- blah blah same thing as above

**Comment by selb** [comment]
Oddly, this one lets you put the bp back on by pressing Q (`SELF x y 5`, as opposed to E `SELF x y -1`). The other one doesn't. This means that it's way less annoying of a bug, but I still want to fix this too if possible.

**Comment by selb** [comment]
#49 is the real solution to both these issues, as well as a number of other long-standing quirks. I'm going to focus on that rather than continuing to hack around each possible case.
