### ISSUE TITLE
Yumlife GitHub page and or the modded client itself may need an accepted use policy.

### ISSUE THREAD

**Issue by QuirkySmirkyIan** [selb/YumLife#67]
It appears that the development team for YumLife may not want bad actors using their services which is very understandable. For better clarification to the end user it may be a good idea to put in a code of conduct for using the mod on public servers ideally posting it to be accessible in H or main menu.

**Comment by selb** [comment]
I don't care how anyone uses YumLife. YumLife is a program you run on your own computer and does not need an AUP.

I suspect you're really talking about OLGC, the replacement for the original phex server that went down. Just like the old server, OLGC is not developed, maintained, hosted, funded, or moderated by me. At the end of the day, they can impose whatever rules they wish on their free hosted service.

The good news is that you can change `phex_ip` to any phex-compatible server you want, and then you don't have to follow the rules of OLGC anymore. If nobody is hosting a phex-compatible server to your taste, you would need to develop and host your own or convince someone like-minded to do that for you.

Since YumLife has scrolling in phex now, maybe I'll make it send `/tos` to the server on connect so the expectations of the phex host are clear. (Then again, that might be annoying to see over and over.)
